import re
from app.models.chunk import Chunk
from app.models.citation import Citation
from app.core.exceptions import CitationValidationError
from app.core.logging import logger


class CitationValidator:
    """Validates citations generated by LLM against provided context chunks."""

    @staticmethod
    def extract_citation_ids(text: str) -> set[str]:
        """Extracts all citation identifiers like 'C1', 'C2' from text format [C1], [C2]."""
        matches = re.findall(r"\[(C\d+)\]", text)
        return set(matches)

    @staticmethod
    def validate_and_map_citations(
        answer_text: str,
        context_chunks: list[Chunk],
        strict: bool = False,
    ) -> tuple[str, list[Citation], str]:
        """
        Validates citations in the answer against context chunks.
        Returns:
            - cleaned_answer: processed answer text
            - citations: list of matched Citation domain objects
            - status: "valid" | "cleaned_invalid" | "unverified"
        """
        valid_chunk_map: dict[str, Chunk] = {
            c.citation_id: c for c in context_chunks if c.citation_id
        }
        valid_ids = set(valid_chunk_map.keys())
        used_ids = CitationValidator.extract_citation_ids(answer_text)

        invalid_ids = used_ids - valid_ids
        status = "valid"

        if invalid_ids:
            msg = f"Invalid/hallucinated citations found in answer: {invalid_ids}. Valid IDs: {valid_ids}"
            logger.warning(msg)
            if strict:
                raise CitationValidationError(msg)
            
            # Remove hallucinated citation tags from text
            cleaned_text = answer_text
            for invalid_id in invalid_ids:
                cleaned_text = re.sub(rf"\[{invalid_id}\]", "", cleaned_text)
            # Normalize excessive spaces created by removal
            cleaned_text = re.sub(r" {2,}", " ", cleaned_text).strip()
            answer_text = cleaned_text
            status = "cleaned_invalid"

        # Build Citation objects for all valid cited chunks
        matched_citations: list[Citation] = []
        for cid in sorted(list(used_ids.intersection(valid_ids)), key=lambda x: int(x[1:])):
            chunk = valid_chunk_map[cid]
            snippet = chunk.text[:200] + ("..." if len(chunk.text) > 200 else "")
            matched_citations.append(
                Citation(
                    id=cid,
                    chunk_id=chunk.id,
                    document_id=chunk.document_id,
                    source=chunk.source,
                    section=chunk.section,
                    page=chunk.page,
                    heading_path=chunk.heading_path,
                    snippet=snippet,
                    score=chunk.score,
                )
            )

        # If answer mentions no citations but context was provided and answer is affirmative
        if not matched_citations and context_chunks and "couldn't find enough information" not in answer_text.lower():
            # Include top 1-2 chunks as background references with status unverified
            for c in context_chunks[:2]:
                if c.citation_id:
                    matched_citations.append(
                        Citation(
                            id=c.citation_id,
                            chunk_id=c.id,
                            document_id=c.document_id,
                            source=c.source,
                            section=c.section,
                            page=c.page,
                            heading_path=c.heading_path,
                            snippet=c.text[:200] + "...",
                            score=c.score,
                        )
                    )
            if status == "valid":
                status = "unverified"

        return answer_text, matched_citations, status
